### PR TITLE
Increase test coverage

### PR DESCRIPTION
**Pull request by GretaCB**
Some low hanging fruit in test coverage. Taking a peek at what's available in mvt-fixtures.

cc @mapsam @springmeyer

### CODE REVIEW

**Comment by GretaCB** [comment]
Not too shabby
screenshot 2018-01-04 12 45 34

Just working on creating a fixture that hits [`Invalid property value type`](https://github.com/mapbox/vtvalidate/blob/master/src/vtvalidate.cpp#L71). Initially thought [mvt-fixture's `011`](https://github.com/mapbox/mvt-fixtures/blob/master/src/011.js#L88) would hit this, but looks like it hits `index out of range: 1` instead. @springmeyer Any thoughts on recreating invalid property type and how that might differ from mvt-fixture `011`?

**Comment by springmeyer** [comment]
@GretaCB great digging inside vtzero 👏 . I think you've uncovered a bug in the fixture in that the fixture has 2 things wrong with it when it should have just one (the one you need). Perhaps the problem is that the tags should be `tags: [0,0],` instead of `tags: [0,1],` at https://github.com/mapbox/mvt-fixtures/blob/bdf4a9bb76016af0c00f059d316b12464d837d11/src/011.js#L103. Can you try changing the fixture in that way and then seeing if it then is able to trigger the error you would expect?

**Comment by GretaCB** [comment]
@springmeyer 💥 that did the trick `illegal property value type`, thank ya!

**Comment by springmeyer** [comment]
Awesome @GretaCB - so happy that mvt-fixtures are helping you move quick here and we're improving the fixtures at the same time 🙌 .

**Pull request merged**
