### PR TITLE
N-api port

### PR DESCRIPTION
**Pull request by artemp**
Universal binaries via `Nan` => `N-API` (`node-addon-api`) port with node 12 built binaries.

More dependency updates are done in later issue #35

### CODE REVIEW

**Comment by OzQu** [comment]
I executed some benchmarkings with existing bench script.

With the master c3c05cf6397 version and node 10

```
*[master]$ node bench/isValid.bench.js --iterations 500 --concurrency 10
Running benchmark...
Benchmark speed: 28736 runs/s (runs: 15000 ms: 522 )
Note: pass --mem to track memory usage
Benchmark iterations:  500 concurrency:  10
*[master]$ node bench/isValid.bench.js --iterations 500 --concurrency 10
Running benchmark...
Benchmark speed: 29528 runs/s (runs: 15000 ms: 508 )
Note: pass --mem to track memory usage
Benchmark iterations:  500 concurrency:  10
```


with the current n-api branch 0e8f02041968 version (which is published as alpha2 binary)

```
*[n-api]$ node bench/isValid.bench.js --iterations 5000 --concurrency 10
Running benchmark...
Benchmark speed: 30625 runs/s (runs: 150000 ms: 4898 )
Note: pass --mem to track memory usage
Benchmark iterations:  5000 concurrency:  10
*[n-api]$ node bench/isValid.bench.js --iterations 5000 --concurrency 10
Running benchmark...
Benchmark speed: 30973 runs/s (runs: 150000 ms: 4843 )
Note: pass --mem to track memory usage
Benchmark iterations:  5000 concurrency:  10
```

Based on just those runs, old master versions might have slight edge.

**Comment by OzQu** [comment]
I ran some repository included benchmarking with current master version for vtvalidate

master version (with node 10)
```
*[master][~/Projects/vtvalidate]$ node bench/isValid.bench.js --iterations 500 --concurrency 10
Running benchmark...
Benchmark speed: 28736 runs/s (runs: 15000 ms: 522 )
Note: pass --mem to track memory usage
Benchmark iterations:  500 concurrency:  10
*[master][~/Projects/vtvalidate]$ node bench/isValid.bench.js --iterations 500 --concurrency 10
Running benchmark...
Benchmark speed: 29528 runs/s (runs: 15000 ms: 508 )
Note: pass --mem to track memory usage
Benchmark iterations:  500 concurrency:  10
```
and with new (node 12 in use)
```
*[n-api][~/Projects/vtvalidate]$ node bench/isValid.bench.js --iterations 500 --concurrency 10
Running benchmark...
Benchmark speed: 26087 runs/s (runs: 15000 ms: 575 )
Note: pass --mem to track memory usage
Benchmark iterations:  500 concurrency:  10
*[n-api][~/Projects/vtvalidate]$ node bench/isValid.bench.js --iterations 500 --concurrency 10
Running benchmark...
Benchmark speed: 26834 runs/s (runs: 15000 ms: 559 )
Note: pass --mem to track memory usage
Benchmark iterations:  500 concurrency:  10
```

New one has significantly better performance in with benchmark tool.

**Comment by axrj** [comment]
Am I interpreting the results wrong? The n-api one seems to take longer as it could do less runs per sec.

**Comment by OzQu** [comment]
That's true, I misread the results.

**Review by mapsam — APPROVED** [review]

**Comment by OzQu** [comment]
Fortunately #37 (node16 + n-api implementation) seems to enhance the performance to be better than node10 + nan implementation, and that will also be deployed in near future.

**Pull request merged**
